spring:
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:postgresql://localhost:5433/sample
    username: sakthi
    password: sakthi

